
    create table Contactos (
        contacto_id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        mail varchar(255),
        nombre varchar(255),
        telefono varchar(255),
        vinculo varchar(255),
        duenio_id integer,
        primary key (contacto_id)
    )

    create table Duenio (
        id integer generated by default as identity (start with 1),
        apellido varchar(255),
        fecha_nacimiento date,
        nombre varchar(255),
        numero_identificacion varchar(255),
        tipo_identificacion varchar(255),
        usuario_usuario_id bigint,
        primary key (id)
    )

    create table Mascota (
        id integer generated by default as identity (start with 1),
        apodo varchar(255),
        descripcionFisica varchar(255),
        edadAproximada double,
        nombre varchar(255),
        sexo integer,
        tipoMascota integer,
        duenio_id integer,
        primary key (id)
    )

    create table Mascota_caracteristicas (
        Mascota_id integer not null,
        caracteristicas_id integer not null
    )

    create table Mascota_fotos (
        Mascota_id integer not null,
        fotos varchar(255)
    )

    create table Rescatistas (
        rescatista_id bigint generated by default as identity (start with 1),
        apellido varchar(255),
        fecha_nacimiento date,
        nombre varchar(255),
        numero_identificacion varchar(255),
        tipo_identificacion varchar(255),
        contacto_id bigint,
        ubicacion_id bigint,
        usuario_id bigint,
        primary key (rescatista_id)
    )

    create table Usuarios (
        usuario_id bigint generated by default as identity (start with 1),
        contrasenia varchar(255),
        nombre_usuario varchar(255),
        tipo_usuario varchar(255),
        primary key (usuario_id)
    )

    create table Voluntarios (
        voluntario_id bigint generated by default as identity (start with 1),
        asociacion_id integer,
        usuario_id bigint,
        primary key (voluntario_id)
    )

    create table asociaciones (
        asociacion_id integer generated by default as identity (start with 1),
        asociacion_nombre varchar(255),
        ubicacion_id bigint,
        primary key (asociacion_id)
    )

    create table caracteristicas (
        tipo varchar(31) not null,
        id integer generated by default as identity (start with 1),
        descripcion varchar(255),
        input_id integer,
        publicacion_adopcion_id integer,
        publicacion_interes_id integer,
        primary key (id)
    )

    create table opciones (
        id integer generated by default as identity (start with 1),
        descripcion varchar(255),
        seleccionada boolean,
        caracteristica_id integer,
        primary key (id)
    )

    create table publiaciones_adopcion (
        id integer generated by default as identity (start with 1),
        activa boolean,
        asociacion_asociacion_id integer,
        duenio_id integer,
        mascota_id integer,
        primary key (id)
    )

    create table publicaciones (
        id integer generated by default as identity (start with 1),
        activa boolean,
        interesado_id integer,
        primary key (id)
    )

    create table publicaciones_rescates (
        publicacion_rescate_id bigint generated by default as identity (start with 1),
        publicacion_rescate_estado varchar(255),
        asociacion_id integer,
        rescate_rescate_id bigint,
        primary key (publicacion_rescate_id)
    )

    create table rescates (
        tipo_rescate varchar(31) not null,
        rescate_id bigint generated by default as identity (start with 1),
        rescate_descripcion varchar(255),
        fecha_nacimiento date,
        ubicacion_id bigint,
        mascota_id integer,
        rescatista_id bigint,
        primary key (rescate_id)
    )

    create table ubicaciones (
        ubicacion_id bigint generated by default as identity (start with 1),
        ubicacion_codigo_postal varchar(255),
        ubicacion_direccion varchar(255),
        ubicacion_latitud numeric,
        ubicacion_localidad varchar(255),
        ubicacion_longitud numeric,
        primary key (ubicacion_id)
    )

    alter table Mascota_caracteristicas 
        add constraint UK_x8h5df7a74tpyg3drpmk93od  unique (caracteristicas_id)

    alter table Contactos 
        add constraint FK_fmgv9k9xocpk0b4o5x4gcpqsy 
        foreign key (duenio_id) 
        references Duenio

    alter table Duenio 
        add constraint FK_5mibpn058fr7fvr6qcxl6paiu 
        foreign key (usuario_usuario_id) 
        references Usuarios

    alter table Mascota 
        add constraint FK_jp5ybetmdo7q1bcwaa1p1mwjs 
        foreign key (duenio_id) 
        references Duenio

    alter table Mascota_caracteristicas 
        add constraint FK_x8h5df7a74tpyg3drpmk93od 
        foreign key (caracteristicas_id) 
        references caracteristicas

    alter table Mascota_caracteristicas 
        add constraint FK_py5tsq0b4bjbjsisej94uie3n 
        foreign key (Mascota_id) 
        references Mascota

    alter table Mascota_fotos 
        add constraint FK_dclevnore3slbildn3hia9nlo 
        foreign key (Mascota_id) 
        references Mascota

    alter table Rescatistas 
        add constraint FK_6p8hx05vyemjbtpoi2npypwvu 
        foreign key (contacto_id) 
        references Contactos

    alter table Rescatistas 
        add constraint FK_xegjxsywco47warso8pm2xfi 
        foreign key (ubicacion_id) 
        references ubicaciones

    alter table Rescatistas 
        add constraint FK_elwsnn5lthcetya4weobsi5nm 
        foreign key (usuario_id) 
        references Usuarios

    alter table Voluntarios 
        add constraint FK_gsh7xgqbntnmg91mafxg6uwc7 
        foreign key (asociacion_id) 
        references asociaciones

    alter table Voluntarios 
        add constraint FK_kj9mxlopn4of0o0mckx2iv1jh 
        foreign key (usuario_id) 
        references Usuarios

    alter table asociaciones 
        add constraint FK_p65rpqdtcf7acm61m5m6oxp4a 
        foreign key (ubicacion_id) 
        references ubicaciones

    alter table caracteristicas 
        add constraint FK_7hmrhuebsf2nco5y3u71j4kn 
        foreign key (input_id) 
        references opciones

    alter table caracteristicas 
        add constraint FK_pyg6qghruqwn589lhyigmi73d 
        foreign key (publicacion_adopcion_id) 
        references publiaciones_adopcion

    alter table caracteristicas 
        add constraint FK_4y77tgg2n86usp53ekd5e8fip 
        foreign key (publicacion_interes_id) 
        references publicaciones

    alter table opciones 
        add constraint FK_8ah80g086ahfprnnv3569xoya 
        foreign key (caracteristica_id) 
        references caracteristicas

    alter table opciones 
        add constraint FK_8ah80g086ahfprnnv3569xoya 
        foreign key (caracteristica_id) 
        references caracteristicas

    alter table publiaciones_adopcion 
        add constraint FK_spvovgx30h291kilylq5eoief 
        foreign key (asociacion_asociacion_id) 
        references asociaciones

    alter table publiaciones_adopcion 
        add constraint FK_3gbf6gcjg1rx2vekobswwhxdy 
        foreign key (duenio_id) 
        references Duenio

    alter table publiaciones_adopcion 
        add constraint FK_fo1la76c1f39gtuxkjjt65bs 
        foreign key (mascota_id) 
        references Mascota

    alter table publicaciones 
        add constraint FK_fwwa5uxomgbn7hbae6bpofd01 
        foreign key (interesado_id) 
        references Duenio

    alter table publicaciones_rescates 
        add constraint FK_97u5f617ytkeyvhmpl3hffx73 
        foreign key (asociacion_id) 
        references asociaciones

    alter table publicaciones_rescates 
        add constraint FK_nwt9vdn2mxvksrtv66ja3vro3 
        foreign key (rescate_rescate_id) 
        references rescates

    alter table rescates 
        add constraint FK_bct178526n9qif1nkoj6uff56 
        foreign key (ubicacion_id) 
        references ubicaciones

    alter table rescates 
        add constraint FK_3kfg88718xkqf3tw8dubyd0db 
        foreign key (mascota_id) 
        references Mascota

    alter table rescates 
        add constraint FK_8ysfq750ehns2h2v4sq77k4cn 
        foreign key (rescatista_id) 
        references Rescatistas
