package domain;

public enum ObjetivoPregunta {
  CARACTERISTICA_MASCOTA,
  PUBLICACION_ADOPCION,
  PUBLICACION_INTERES_ADOPCION_COMODIDAD,
  PUBLICACION_INTERES_ADOPCION_PREFERENCIA,
  PREGUNTA_ASOCIACION
}
